---
- name: release update post installation on database
  environment:
     ORACLE_HOME: "{{ ORACLE_HOME }}"
     ORACLE_SID: "{{ ORACLE_SID }}"
     PATH: "{{ ORACLE_HOME }}/OPatch:/usr/ccs/bin:$PATH"
  ansible.builtin.shell:
    cmd: datapatch -verbose
  register: datapatch

- name: display datapatch output
  debug:
    var: datapatch.stdout_lines

- name: copy the datapatch command output to a log file
  copy:
    content: "{{ datapatch.stdout }}"
    dest: "{{ log_dir }}/datapatch_status_{{ ORACLE_SID }}_{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}"