---
- name: Upgrade OPatch Utility 
  ansible.builtin.shell:
    cmd: mv {{ ORACLE_HOME }}/OPatch {{ ORACLE_HOME }}/OPatch_{{ lookup('pipe', 'date +%Y%m%d-%H%M') }}; unzip -d {{ORACLE_HOME }} {{ patch_dir }}/p6880880_122010_Linux-x86-64.zip

- name: Verify OPatch Utility Version 
  ansible.builtin.shell:
    cmd: export ORACLE_HOME="{{ ORACLE_HOME }}";$ORACLE_HOME/OPatch/opatch version
  register: db_home_opatch_version 

- name: display database home OPatch Utility Version
  debug:
    var: db_home_opatch_version.stdout_lines

- name: copy release update to the local patch directory
  ansible.builtin.shell:
    cmd: cp -r {{ patch_dir }}/{{ gi_patch_id }} {{ patch_local_dir }}
    
- name: Verify database home patch conflict
  ansible.builtin.shell: 
    cmd: cd {{ patch_local_dir }}/{{ gi_patch_id }}/{{ db_patch_id }};export ORACLE_HOME="{{ ORACLE_HOME }}";export PATH={{ ORACLE_HOME }}/OPatch:/usr/ccs/bin:$PATH;opatch prereq CheckConflictAgainstOHWithDetail -ph .
  register: db_home_conflict_status 

- name: display database home patch conflict output
  debug:
    var: db_home_conflict_status.stdout_lines